name: Go package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: make
        run: make init
        
      - name: make
        run: make all
        
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
